---
- name: Include vars
  ansible.builtin.import_tasks: include-vars.yml

- name: Import Redhat task
  ansible.builtin.import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Standalone install method choosed
  ansible.builtin.import_tasks: install-with-package.yml
  when: certbot_install_method == 'package'

- name: Snap install method choosed
  ansible.builtin.import_tasks: install-with-snap.yml
  when: certbot_install_method == 'snap'

- name: Source install method choosed
  ansible.builtin.import_tasks: install-from-source.yml
  when: certbot_install_method == 'source'

- name: Create certs for standalone install
  ansible.builtin.include_tasks: create-cert-standalone.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'standalone'
  loop_control:
    loop_var: cert_item

- name: Create certs for webroot install
  ansible.builtin.include_tasks: create-cert-webroot.yml
  with_items: "{{ certbot_certs }}"
  when:
    - certbot_create_if_missing
    - certbot_create_method == 'webroot'
  loop_control:
    loop_var: cert_item

- name: Check cron jobs
  ansible.builtin.import_tasks: renew-cron.yml
  when: certbot_auto_renew
