---
# See: https://github.com/geerlingguy/ansible-role-certbot/issues/107
- name: Check dnf modules for Redhat family
  when:
  - ansible_distribution == 'CentOS'
  - ansible_distribution_major_version | int >= 8
  block:
  - name: Ensure dnf-plugins are installed on CentOS 8+.
    ansible.builtin.yum:
      name: dnf-plugins-core
      state: present

    when: ansible_facts['distribution_version'] is version('8.2', '<=')
  - name: Check dnf modules for Centos
    block:
    - name: Enable DNF module for CentOS 8.3+.
      ansible.builtin.shell: |
        dnf config-manager --set-enabled powertools
      register: dnf_module_enable
      changed_when: false
      when: ansible_facts['distribution_version'] is version('8.3', '>=')

    - name: Enable DNF module for CentOS 8.0–8.2.
      ansible.builtin.shell: |
        dnf config-manager --set-enabled PowerTools
      register: dnf_module_enable
      changed_when: false

- name: Ensure dnf-plugins are installed on Rocky/AlmaLinux.
  yum:
    name: dnf-plugins-core
    state: present

- name: Enable DNF module for Rocky/AlmaLinux.
  shell: |
    dnf config-manager --set-enabled crb
  changed_when: false