---
- name: Converge
  hosts: all
  become: true

  vars:
    certbot_install_from_source: true
    certbot_auto_renew_user: root

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - geerlingguy.git
    - geerlingguy.certbot
